Update the readme file with environment setup instructions
LSFLK/MedicinesforLK pull request #121
Opened 2022-07-11 12:31 UTC by Bawanthathilan

## Purpose

The purpose of this PR is to fix #117 

## Goals

Update the readme file with environment setup instructions

## Approach

### Screenshots

![image](https://user-images.githubusercontent.com/38850236/178264600-06ed4acc-44f2-4bb8-8118-152e2c9c7038.png)

## Related PRs
 

## Learning

2022-07-11 15:25 UTC, jayasanka-sack requested changes
Thanks @Bawanthathilan , I added a comment.

2022-07-12 05:19 UTC, jayasanka-sack requested changes
@Bawanthathilan, the correct readme should be the readme file of the root directory. 

Please delete `donor-portal/README.md` and `admin-portal/README.md` files

2022-07-12 05:22 UTC, Bawanthathilan commented
> @Bawanthathilan, the correct readme should be the readme file of the root directory.
> 
> Please delete `donor-portal/README.md` and `admin-portal/README.md` files

sure

2022-07-12 06:27 UTC, jayasanka-sack commented on README.md
>  2. Ballerina - Latest
No longer needed as we moved backend to separate repos. 
```suggestion
```

2022-07-12 07:01 UTC, jayasanka-sack approved these changes
Thanks @Bawanthathilan !

2022-07-12 07:03 UTC, merged