handle aid package publish with mock api
LSFLK/MedicinesforLK pull request #32
Opened 2022-07-01 12:18 UTC by kulathilake

Handles aid package publish with

2022-07-02 11:01 UTC, nipuna777 approved these changes
Looks great! Thanks. Left a few comments, but no blockers. 

Could we run prettier on this and merge it in.

2022-07-02 11:01 UTC, nipuna777 commented on admin-portal/src/pages/aidPackage/aidPackage.tsx
> +      throw new Error('invalid supplier') // or handle otherwise.
Is it possible to reach this error?

2022-07-07 14:45 UTC, jayasanka-sack commented
@nipuna777 Shall we merge this PR?

2022-07-07 15:21 UTC, jayasanka-sack requested changes
Thanks for getting this done @nipuna777 !

I added some styling suggestions.

2022-07-07 15:21 UTC, jayasanka-sack commented on admin-portal/src/types/MedicalNeeds.ts
> +export type MedicalNeed = {
Let's use interfaces to keep consistent as we have used interfaces for other types.

2022-07-07 15:21 UTC, jayasanka-sack commented on admin-portal/src/types/MedicalNeeds.ts
> +export type MedicalNeed = {
Also, let's make one file per interface.

2022-07-07 15:21 UTC, jayasanka-sack commented on admin-portal/src/pages/aidPackage/aidPackage.tsx
> +        .then(() => {
Let's use Async/await instead of `then`. 
Just to maintain the consistency in the codebase.

2022-07-07 15:21 UTC, jayasanka-sack commented on admin-portal/src/pages/aidPackage/aidPackage.tsx
> +};
Interfaces over types. 
Just to maintain the consistency in the codebase.

2022-07-08 15:36 UTC, merged