Edit footer UI changes
LSFLK/MedicinesforLK pull request #322
Opened 2022-08-01 11:46 UTC by RandilaP

## Purpose

The purpose of this PR is to fix #316 

## Goals
-Update footer UI

### Screenshots
![image](https://user-images.githubusercontent.com/106733522/182141193-15d8c31c-54e5-41d1-a486-b1a96f8366c5.png)

2022-08-01 13:44 UTC, anjula-sack requested changes

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/styles.css
> +
Remove this empty line

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/styles.css
> +
Remove this empty lines

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/styles.css
> +
same here

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/styles.css
> +
Remove the empty line

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/styles.css
> +
same here

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/styles.css
> +
same here

2022-08-01 13:44 UTC, anjula-sack commented on donor-portal/src/components/footer/index.tsx
> +            Our Legal Status in Sri Lanka{" "}
```suggestion
            Our Legal Status in Sri Lanka
```

2022-08-01 16:38 UTC, jayasanka-sack requested changes

2022-08-02 01:36 UTC, jayasanka-sack approved these changes
Thanks for getting this done @RandilaP !

2022-08-02 01:36 UTC, merged