Add newsletter section styles
LSFLK/MedicinesforLK pull request #582
Opened 2022-12-14 13:16 UTC by Madhawa97

## Purpose

The purpose of this PR is to fix #581 

## Goals

To improve the styles of the subscription form

## Approach

Choose a suitable design and improve the style

### Screenshots
![Screenshot 2022-12-14 at 18 43 03](https://user-images.githubusercontent.com/70215958/207605096-aa1cc098-8c8e-4806-a5cc-343bc18192ca.jpg)

## Related PRs
 
None

2022-12-14 13:19 UTC, anjula-sack commented
Thank you @Madhawa97 Shall we use black as the bg colour and do the styling? So we can make it look like a part of the footer/

2022-12-14 13:23 UTC, Madhawa97 commented
Sure @anjula-sack.

2022-12-14 13:41 UTC, Madhawa97 commented
Update: 

![Screenshot 2022-12-14 at 19 11 42](https://user-images.githubusercontent.com/70215958/207610562-18850bd6-bbe7-4fc8-bb3c-3037d7a6ec67.jpg)

2022-12-14 14:13 UTC, anjula-sack requested changes

2022-12-14 14:59 UTC, Madhawa97 commented on donor-portal/src/components/SubscriptionForm/styles.css
> +}
Done @anjula-sack

2022-12-14 15:28 UTC, anjula-sack commented on donor-portal/src/components/SubscriptionForm/index.tsx
> +            className=""
```suggestion
```

2022-12-14 15:44 UTC, anjula-sack approved these changes
Good job! @Madhawa97

2022-12-14 15:44 UTC, merged

2022-12-15 12:15 UTC, Madhawa97 commented
Thank you @anjula-sack